name: pr

on:
 pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: go.mod
          cache-dependency-path: go.sum
      -
        name: Install Dependencies
        run: |
          make generate_ebpf_in_docker
          go mod download -x
      # -
      #   name: Run Tests
      #   run: go test ./...
      -
        name: Build Binary
        run: make build
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: quay.io/groundcover/caretta
